project_id = "ujwcwxprmyeqsbzjcokk"

[functions.ai-companion]
verify_jwt = false

[functions.deploy-response-team]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.paystack-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-email]
verify_jwt = false
